<?php

/*
 * This file is part of the 'octris/tpl' package.
 *
 * (c) Harald Lapp <harald@octris.org>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Octris\Tpl\Extension;

/**
 * Extension base class.
 *
 * @copyright   copyright (c) 2018-present by Harald Lapp
 * @author      Harald Lapp <harald@octris.org>
 */
abstract class AbstractExtension
{
    /**
     * Name of extension.
     *
     * @var     string
     */
    private $name = '';

    /**
     * Callback implementing code generator.
     *
     * @var     callable
     */
    private $fn = null;

    /**
     * Extension options.
     *
     * @var     array
     */
    private $options = [];

    /**
     * Number of parameters.
     * 
     * @var     array|null
     */
    private $pnumber = null;

    /**
     * Constructor.
     *
     * @param   string              $name               Name to register extension with.
     * @param   callable            $fn                 Callback implementing code generator.
     * @param   array               $options            Optional options.
     */
    public function __construct($name, callable $fn, array $options = [])
    {
        $this->name = $name;
        $this->fn = $fn;
        $this->options = $options + [ 'final' => false, 'env' => false ];
    }

    /**
     * Return name of extension.
     *
     * @return  string
     */
    public function getName()
    {
        return $this->name;
    }

    /**
     * Return min,max number of parameters.
     *
     * @return  array
     */
    final public function getNumberOfParameters()
    {
        if (is_null($this->pnumber)) {
            $this->pnumber = \Octris\Tpl\Extension::getNumberOfParameters($this->fn);
        }

        return $this->pnumber;
    }

    /**
     * Return code generated by extension.
     *
     * @param   array               $args               Extension arguments definition.
     * @param   array               $env                Engine environment.
     * @return  array                                   Generated code.
     */
    abstract public function getCode(array $args, array $env);

    /**
     * Return code-generator callable.
     *
     * @param   array               $env                Environment to optionally pass to the callable.
     * @return  object
     */
    final protected function getFn(array $env)
    {
        if ($this->options['env']) {
            $return = $this->fn->bindTo(new class($env) extends Env { });
        } else {
            $return = $this->fn;
        }

        return $return;
    }

    /**
     * Return option.
     *
     * @param   string              $name               Name of option to return.
     * @return  mixed                                   Option value.
     */
    protected function getOption($name)
    {
        return $this->options[$name];
    }

    /**
     * Return if extension is defined as final and cannot be overwritten by an extension
     * of the same name.
     *
     * @return  bool
     */
    public function isFinal()
    {
        return ($this->options['final']);
    }
}
